### PR TITLE
Add initDB func

### PR DESCRIPTION
**Pull request by negbie**
Hey, I wanted to test the non docker version and got immediately bored by the Readme instructions. The only thing I want is to see at the top of the Readme is some lines of text and in the best case lot's of cat pics but not Create User, Create Role, Create DB, bake a cake, visit your grandma and so on. Just give the user a init func for the first time ;) Like

./homer-app -initialize_db -database-host=localhost -database-root-user=postgres -database-root-password=root

### CODE REVIEW

**Comment by negbie** [comment]
Btw you should really split the main.go into smaller pieces. 1000 lines in the main.go is hard to read ;)

**Comment by negbie** [comment]
Another thing is naming convention. Sometimes it's db sometimes database. Maybe just call it database and use a verb infront of functions.

**Comment by negbie** [comment]
For this pr I followed your convention to use db since it's a func.

**Comment by adubovikov** [comment]
super! again, thank you!

**Pull request merged**
