### PR TITLE
Simplify db keepalive startup setting

### PR DESCRIPTION
**Pull request by systemcrash**
(i.e. whether a comma follows it or not)

Ensures that the keepalive boolean setting can appear on any row in the block (and optionally have a comma follow it) following later edits.

### CODE REVIEW

**Comment by lmangani** [comment]
Why are we not simply making this a default in the JSON without the sed hackery?

**Comment by adubovikov** [comment]
I have just changed the code and set the keepalive param to true by default. This settings it's not need anymore. Anyway, thank you for your request. I will close it.

**Comment by systemcrash** [comment]
It IS a default. Some will want to change it.

Problem is that it’s not quoted. You’re welcome to make your own
contraption which will do the same job.

**Comment by systemcrash** [comment]
Sure. If jq is available in the image. I think making this the default and
not being able to switch it off is a bit much. The mechanism floods the
logs with the ping...

**Comment by lmangani** [comment]
@systemcrash I think you misunderstood. The docker container uses its own fork of the config where parameters have a unique replacement key. So what i would do is the following as per other seeings:

#### Make the default a key (not true or false yet)

```
 "database_config": {
    "user": "homer_user",
    "pass": "homer_password",
    "name": "homer_config",
    "host": "homer_db_host",
    "keepalive": homer_db_keepalive
  },
```
Have the script deploy the default or setting:
```
DB_KEEPALIVE=${DB_KEEPALIVE:-true}
 if [ -n "$DB_KEEPALIVE" ]; then sed -i "s/homer_db_keepalive/${DB_KEEPALIVE}/g" /usr/local/homer/etc/webapp_config.json; fi
```

**Comment by systemcrash** [comment]
What did I misunderstand?:

> I have just changed the code and set the keepalive param to true by default. This settings it's not need anymore. Anyway, thank you for your request. I will close it.

**Comment by systemcrash** [comment]
> @systemcrash I think you misunderstood. The docker container uses its own fork of the config where parameters have a unique replacement key. So what i would do is the following as per other seeings:
> #### Make the default a key (not true or false yet)
> 
> ```
>  "database_config": {
>     "user": "homer_user",
>     "pass": "homer_password",
>     "name": "homer_config",
>     "host": "homer_db_host",
>     "keepalive": homer_db_keepalive
>   },
> ```
> 
> Have the script deploy the default or setting:
> 
> ```
> DB_KEEPALIVE=${DB_KEEPALIVE:-true}
>  if [ -n "$DB_KEEPALIVE" ]; then sed -i "s/homer_db_keepalive/${DB_KEEPALIVE}/g" /usr/local/homer/etc/webapp_config.json; fi
> ```
> 
> This way it doesn't matter where the setting is (or are) and there's no JSON complications

Much simpler. I was going on the assumption that it should be one or the other already at startup, to avoid other problems.

**Comment by lmangani** [comment]
> Much simpler. I was going on the assumption that it should be one or the other already at startup, to avoid other problems. ( plus setting it to `homer_db_keepalive` triggers JSON parse errors )

Nice! btw I tried to find a way to use the real config sample, but ultimately decided to provide the containers with a custom config fork and the above approach - the only challenge is we need to keep it in sync but its worth it in terms of simplicity and predictability.

**Comment by systemcrash** [comment]
OK - all fixed, with some to_lower magic in there. Should avoid any weird shells or ppl writing TRUE or True (JSON parse error)

**Comment by lmangani** [comment]
Thanks for your contribution and interaction!

**Comment by lmangani** [comment]
I'm triggering a rebuild of the containers to test it next. Shall be online in about 10m

**Pull request merged**
