### PR TITLE
Docker LDAP variables override

### PR DESCRIPTION
**Pull request by wurwik**
Added homer docker additional LDAP variables override, and added additional LDAP settings into webapp_config.json docker version.

### CODE REVIEW

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Thanks for your contribution @wurwik could you kindly sign the CLA to trigger the automated build process?

**Comment by wurwik** [comment]
Approved CLA

**Comment by agrigorjevs** [comment]
@lmangani it seems that the latest docker hub image build was built with cache and the new changes are not present in the docker image.

**Comment by lmangani** [comment]
The builder should be using [no-cache](https://github.com/sipcapture/homer-app/blob/master/scripts/build_docker.sh#L24) by default, have you tried a local build to confirm?

**Comment by wurwik** [comment]
On my local machine build fails when running "make docker". 
I also have tried to run separately "make build" and "make frontend", and fails with the same error on step "make frontend".
Here the output of "make docker"[output.txt](https://github.com/sipcapture/homer-app/files/8049208/output.txt)

**Comment by agrigorjevs** [comment]
@lmangani running `docker run --rm sipcapture/webapp cat docker-entrypoint.d/1` does not reveal that the changes in this PR are present in the latest Docker Hub image.

**Comment by lmangani** [comment]
I think I see where the problem is, let me unblock the CI pipeline and confirm back.

**Comment by wurwik** [comment]
The latest build on the docker hub contains the latest changes! Thank You!

**Pull request merged**
