### PR TITLE
Create unique_index for username

### PR DESCRIPTION
**Pull request by ghmj2417**
In addition to creating a unique index, I updated the username column in users varchar length to match dashboards.

### CODE REVIEW

**Comment by adubovikov** [comment]
the dashboard should not have an uniq index for username - there you can have multiple records. In worse case the uniq ID should be "username+dashboard ID"

**Comment by ghmj2417** [comment]
I was afraid that you might say that about dashboards.  In the user_settings table I see that a user's row will get deleted and then inserted for every time they browse the dashboard.  I was hoping the idea would be that the user's dashboard information would be stored in the data column and they would only have one row in the table.

**Comment by ghmj2417** [comment]
In regards to the CLA, I did sign it.  However, I realized, after the fact, that my email was not set for the first commit.  If need be, I can close this PR and open a new one so I follow the process correctly.

**Comment by adubovikov** [comment]
> I was afraid that you might say that about dashboards. In the user_settings table I see that a user's row will get deleted and then inserted for every time they browse the dashboard. I was hoping the idea would be that the user's dashboard information would be stored in the data column and they would only have one row in the table.

no, the user_settings can have mutiple different values. Therefore the username index should not be an uniq.

**Comment by ghmj2417** [comment]
For dashboards, what if we did either the guid or guid+username as a unique index?

**Comment by adubovikov** [comment]
GUID is already uniq

**Comment by adubovikov** [comment]
> In regards to the CLA, I did sign it. However, I realized, after the fact, that my email was not set for the first commit. If need be, I can close this PR and open a new one so I follow the process correctly.

Yes, please do, otherwise we will have an error

**Pull request closed without merging**
