### PR TITLE
fix sed LDAP_ADMINGROUP, when sed changes all words admin in the line

### PR DESCRIPTION
**Pull request by perrfect**

### CODE REVIEW

**Comment by perrfect** [comment]
@adubovikov Can you see this PR, please?

**Comment by adubovikov** [comment]
Looks good for me! Thank you!

**Comment by perrfect** [comment]
@adubovikov Thank you too.
By the way, can you add these changes to the **sipcapture/webapp** docker image on docker hub?

**Comment by adubovikov** [comment]
yes, we will do it tonigt

**Pull request merged**
